# permissions for end users to view benthospipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: benthospipeline-viewer-role
rules:
- apiGroups:
  - ingtra.net
  resources:
  - benthospipelines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ingtra.net
  resources:
  - benthospipelines/status
  verbs:
  - get
